title: Amir Sarkaboudi
email: amirsarkaboudi@asu.edu
description: >-
  Cognitive science | Agent-based modeling | Network dynamics
github_username: amirhsarkaboudi
#theme: jekyll-theme-minimal
#theme: null
theme: jekyll-theme-midnight

profile_image: /assets/20250324_171905.png

# Author info (optional, but useful)
author:
  name: Amir Sarkaboudi
  email: amirsarkaboudi@asu.edu

# Social links (custom keys for your use in HTML)
social_links:
  - title: GitHub
    url: https://github.com/amirhsarkaboudi
  - title: LinkedIn
    url: https://www.linkedin.com/in/amirhossein-sarkaboudi-569003251/

# Tabs for manual nav bar on homepage (not used by the theme itself)
navigation:
  - title: Home
    url: /
  - title: CV
    url: /cv
  - title: Projects
    url: /projects
  - title: Talks
    url: /talks
